name: "Check pnpm Overrides"
description: "Checks whether pnpm overrides are still necessary by running audit without them."
author: "Maximilian Franzke"
runs:
  using: "composite"
  steps:
      # Install action dependencies
      - name: Install action dependencies
        run: |
          cd ${{ github.action_path }}
          pnpm install --prod
        shell: bash
        
      # Ensure we have git configured for commits
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash
        
      # Save original state for comparison
      - name: Save current state
        run: |
          git add .
          git stash push -m "backup-before-override-removal" || true
        shell: bash

      # Remove overrides and let pnpm fix issues
      - name: Remove overrides and fix with pnpm
        run: |
          node ${{ github.action_path }}/scripts/remove-overrides.js
          pnpm install --no-frozen-lockfile
          pnpm audit --fix || true
        shell: bash

      # Check if anything changed
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected after removing overrides and running audit --fix"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected after removing overrides and running audit --fix"
            echo "Changed files:"
            git diff --name-only
            git diff --cached --name-only
          fi
        shell: bash

      # Generate summary of changes for PR/comment
      - name: Generate change summary
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          echo "# pnpm Overrides Removal Summary" > override-removal-summary.md
          echo "" >> override-removal-summary.md
          echo "The following changes occurred after removing pnpm overrides and running \`pnpm audit --fix\`:" >> override-removal-summary.md
          echo "" >> override-removal-summary.md
          echo "## Changed Files" >> override-removal-summary.md
          git diff --name-only >> override-removal-summary.md
          git diff --cached --name-only >> override-removal-summary.md
          echo "" >> override-removal-summary.md
          echo "## Summary" >> override-removal-summary.md
          echo "- Removed overrides from configuration files" >> override-removal-summary.md
          echo "- Ran \`pnpm install\` to update lockfile" >> override-removal-summary.md  
          echo "- Ran \`pnpm audit --fix\` to apply available fixes" >> override-removal-summary.md
          echo "" >> override-removal-summary.md
          echo "This suggests that the overrides are no longer necessary as pnpm can now resolve dependencies and fix vulnerabilities without them." >> override-removal-summary.md
        shell: bash

      # If on PR, post comment about changes
      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.changes.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            const summary = fs.readFileSync('override-removal-summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            })

      # If on default branch and changes detected, create PR
      - name: Create PR for override removal
        if: steps.changes.outputs.has_changes == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: remove unnecessary pnpm overrides"
          title: "Remove unnecessary pnpm overrides"
          body-path: override-removal-summary.md
          branch: remove-unneeded-pnpm-overrides
          base: ${{ github.event.repository.default_branch }}

      # If no changes, restore original state
      - name: Restore original state if no changes
        if: steps.changes.outputs.has_changes == 'false'
        run: |
          git stash pop || true
          echo "No changes were needed - overrides are still necessary"
        shell: bash
