name: "Check pnpm Overrides"
description: "Checks whether pnpm overrides are still necessary by running audit without them."
author: "Maximilian Franzke"
runs:
  using: "composite"
  steps:
      # Install action dependencies
      - name: Install action dependencies
        run: |
          cd ${{ github.action_path }}
          pnpm install --prod
        shell: bash
        
      # Audit WITH overrides
      - name: Install dependencies (with overrides)
        run: pnpm install
        shell: bash
      - name: Run pnpm audit (with overrides)
        run: pnpm audit --json > audit-with.json || true
        shell: bash

      # Save original files
      - name: Backup package.json and pnpm-workspace.yaml
        run: |
          cp package.json package.json.bak
          if [ -f pnpm-workspace.yaml ]; then
            cp pnpm-workspace.yaml pnpm-workspace.yaml.bak
          fi
        shell: bash

      # Remove overrides
      - name: Remove overrides
        run: node ${{ github.action_path }}/scripts/remove-overrides.js
        shell: bash

      # Audit WITHOUT overrides
      - name: Install dependencies (without overrides)
        run: pnpm install --no-frozen-lockfile
        shell: bash
      - name: Run pnpm audit (without overrides)
        run: pnpm audit --json > audit-without.json || true
        shell: bash

      # Compare audits
      - name: Compare audit results
        id: diff
        run: node ${{ github.action_path }}/scripts/compare-audits.js
        shell: bash

      # Restore original files
      - name: Restore original package.json and pnpm-workspace.yaml
        run: |
          mv package.json.bak package.json
          if [ -f pnpm-workspace.yaml.bak ]; then
            mv pnpm-workspace.yaml.bak pnpm-workspace.yaml
          fi
        shell: bash

      # If on PR, post comment
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            const diffText = fs.readFileSync('audit-diff.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**pnpm overrides check**\n\n${diffText}`
            })

      # If on default branch (manual/scheduled), create PR if safe to remove overrides
      - name: Remove overrides and update lockfile
        if: steps.diff.outputs.can_remove_overrides == 'true' && github.event_name != 'pull_request'
        run: |
          node ${{ github.action_path }}/scripts/remove-overrides.js
          pnpm install
        shell: bash

      - name: Commit and create PR
        if: steps.diff.outputs.can_remove_overrides == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: remove unnecessary pnpm overrides"
          title: "Remove unnecessary pnpm overrides"
          body: |
            This PR removes `pnpm` overrides that are no longer needed because vulnerabilities have been fixed upstream.
            Please verify that everything installs and works as expected.
          branch: remove-unneeded-pnpm-overrides
          base: ${{ github.event.repository.default_branch }}
